### ISSUE TITLE
discord-get-message node question

### ISSUE THREAD

**Issue by Nagamakii** [madmax3365/node-red-node-discord#10]
I am trying to make a discord bot that turns on lights on a raspberry pi, so I was curious if it was possible to make the node process the specific commands such as !red, !green, etc. since (correct me if im wrong) all the node does by default is pass the msg.payload. I have little to no experience with JS so bare with me in the that aspect. Thanks!

**Comment by madmax3365** [comment]
Hey @Nagamakii. If I understood you correctly, you want to turn lights based on the received message? 
If so, you must process message and related logic in another node, for example in `function node`. 
 I don't think that this has anything to do with the `discord node` itself.

**Comment by Nagamakii** [comment]
> 
> 
> Hey @Nagamakii. If I understood you correctly, you want to turn lights based on the received message?
> If so, you must process message and related logic in another node, for example in `function node`.
> I don't think that this has anything to do with the `discord node` itself.

ok I see, thank you!
