### ISSUE TITLE
TypeError: msg.attachments.forEach is not a function

### ISSUE THREAD

**Issue by chrzr** [madmax3365/node-red-node-discord#21]
Hi there!

I'm trying to attach a picture from a local IP-Cam to a message. I use the HTTP Request node to GET the picture and return it as a binary buffer to msg.payload. 
I then use a function node to build msg.attachments:

![image](https://user-images.githubusercontent.com/17109454/103490929-85c27b00-4e1f-11eb-9bb0-471ddc69ac72.png)

However, I only get "TypeError: msg.attachments.forEach is not a function". 

![image](https://user-images.githubusercontent.com/17109454/103490902-43993980-4e1f-11eb-9b40-f9c8bb43ac08.png)

Any idea what could cause this? 

Thanks in advance!

**Comment by madmax3365** [comment]
Hi @chrzr . I think the `attachments` property must be an array.
Try to pass an array containing your image object.

**Comment by chrzr** [comment]
Ah damn, that's it!
Thank you! :-)
